# Generated by Django 4.2.27 on 2026-04-12 23:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[
                            (100, "100 Level"),
                            (200, "200 Level"),
                            (300, "300 Level"),
                            (400, "400 Level"),
                            (500, "500 Level"),
                        ],
                        default=100,
                        help_text="Student level for this course",
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("departmental", "Departmental (Single Department)"),
                            ("shared", "Shared (Specific Departments)"),
                            ("general", "General (All Departments)"),
                        ],
                        default="departmental",
                        help_text="Whether this course is for one department, shared, or general",
                        max_length=20,
                    ),
                ),
                (
                    "units",
                    models.PositiveIntegerField(
                        help_text="Number of course units (1-6)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "hours",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Total weekly lecture hours",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "student_count",
                    models.PositiveIntegerField(
                        help_text="Total expected number of students (across all departments if shared)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "shared_session_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier for courses that should be taught in the same session (cross-listed)",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="timetable.college",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LectureHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum number of students the hall can hold",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "hall_type",
                    models.CharField(
                        choices=[
                            ("department", "Department-Specific"),
                            ("shared", "Shared (Multiple Departments)"),
                            ("general", "General (All Departments)"),
                        ],
                        default="department",
                        max_length=20,
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Departments that can use this hall (for department-specific or shared halls)",
                        related_name="lecture_halls",
                        to="timetable.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("staff_id", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturers",
                        to="timetable.college",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "start_hour",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(17),
                        ]
                    ),
                ),
                (
                    "end_hour",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(9),
                            django.core.validators.MaxValueValidator(18),
                        ]
                    ),
                ),
            ],
            options={
                "ordering": ["day", "start_hour"],
                "unique_together": {("day", "start_hour", "end_hour")},
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_number", models.PositiveIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="timetable.course",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="timetable.lecturehall",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="timetable.lecturer",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="timetable.timeslot",
                    ),
                ),
            ],
            options={
                "ordering": ["time_slot__day", "time_slot__start_hour"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                help_text="Primary/owning department",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="timetable.department",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                help_text="Lecturer assigned to teach this course",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="timetable.lecturer",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="shared_departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other departments that also take this course (for shared/general courses)",
                related_name="shared_courses",
                to="timetable.department",
            ),
        ),
        migrations.CreateModel(
            name="LecturerUnavailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unavailable_days",
                        to="timetable.lecturer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lecturer Unavailabilities",
                "unique_together": {("lecturer", "day")},
            },
        ),
    ]
