# Generated by Django 4.2.27 on 2026-04-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecturehall",
            name="departments",
        ),
        migrations.AddField(
            model_name="lecturehall",
            name="colleges",
            field=models.ManyToManyField(
                blank=True,
                help_text="Colleges that can use this hall (for college-specific or shared halls)",
                related_name="lecture_halls",
                to="timetable.college",
            ),
        ),
        migrations.AlterField(
            model_name="lecturehall",
            name="hall_type",
            field=models.CharField(
                choices=[
                    ("college", "College-Specific"),
                    ("shared", "Shared (Multiple Colleges)"),
                    ("general", "General (All Colleges)"),
                ],
                default="college",
                max_length=20,
            ),
        ),
    ]
