# Generated by Django 4.2.27 on 2026-04-04 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="hours",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Total weekly lecture hours",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
