# Generated by Django 4.2.27 on 2026-04-21 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lecturerunavailability",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="lecturerunavailability",
            name="end_hour",
            field=models.PositiveIntegerField(
                default=18,
                help_text="End of unavailability (e.g., 18 for 6 PM)",
                validators=[
                    django.core.validators.MinValueValidator(8),
                    django.core.validators.MaxValueValidator(18),
                ],
            ),
        ),
        migrations.AddField(
            model_name="lecturerunavailability",
            name="start_hour",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Start of unavailability (e.g., 8 for 8 AM)",
                validators=[
                    django.core.validators.MinValueValidator(8),
                    django.core.validators.MaxValueValidator(18),
                ],
            ),
        ),
    ]
