# Generated by Django 4.2.27 on 2026-04-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timetable",
            "0002_remove_lecturehall_departments_lecturehall_colleges_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturehall",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
