# Generated by Django 4.2.27 on 2026-04-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_course_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="shared_session_id",
            field=models.CharField(
                blank=True,
                help_text="Identifier for courses that should be taught in the same session (cross-listed)",
                max_length=50,
                null=True,
            ),
        ),
    ]
