# Generated by Django 4.2.27 on 2026-04-13 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0003_alter_lecturehall_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary/owning department (optional for general courses)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="timetable.department",
            ),
        ),
    ]
