# Generated by Django 4.2.27 on 2026-04-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0004_alter_course_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="college",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="timetable.college",
            ),
            preserve_default=False,
        ),
    ]
