# Generated by Django 4.2.27 on 2026-04-14 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0005_alter_department_college"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="lecturer",
            field=models.ForeignKey(
                default=1,
                help_text="Lecturer assigned to teach this course",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="timetable.lecturer",
            ),
            preserve_default=False,
        ),
    ]
