# Generated by Django 4.2.27 on 2026-04-14 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0006_alter_course_lecturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_course_code",
                        message="Course code must contain both letters and numbers.",
                        regex="^(?=.*[a-zA-Z])(?=.*\\d).+$",
                    )
                ],
            ),
        ),
    ]
